// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VTOP_H_
#define VERILATED_VTOP_H_  // guard

#include "verilated_heavy.h"
#include "verilated_save.h"

//==========

class Vtop__Syms;
class Vtop_VerilatedVcd;
class Vtop___024unit;


//----------

VL_MODULE(Vtop) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    Vtop___024unit* __PVT____024unit;

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clk_48,0,0);
    VL_IN8(reset,0,0);
    VL_OUT8(VGA_R,7,0);
    VL_OUT8(VGA_G,7,0);
    VL_OUT8(VGA_B,7,0);
    VL_OUT8(VGA_HS,0,0);
    VL_OUT8(VGA_VS,0,0);
    VL_OUT8(VGA_HB,0,0);
    VL_OUT8(VGA_VB,0,0);
    VL_IN8(ioctl_download,0,0);
    VL_IN8(ioctl_upload,0,0);
    VL_IN8(ioctl_wr,0,0);
    VL_IN8(ioctl_dout,7,0);
    VL_IN8(ioctl_din,7,0);
    VL_IN8(ioctl_index,7,0);
    VL_OUT8(ioctl_wait,0,0);
    VL_OUT8(ce_pix,0,0);
    VL_IN16(inputs,11,0);
    VL_OUT16(AUDIO_L,15,0);
    VL_OUT16(AUDIO_R,15,0);
    VL_IN16(ps2_key,10,0);
    VL_IN(ioctl_addr,24,0);

    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_RESETn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Res_n_i;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_24;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lRELOAD_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__RESET_INT;
    CData/*0:0*/ top__DOT__clk_48;
    CData/*0:0*/ top__DOT__reset;
    CData/*7:0*/ top__DOT__VGA_R;
    CData/*7:0*/ top__DOT__VGA_G;
    CData/*7:0*/ top__DOT__VGA_B;
    CData/*0:0*/ top__DOT__VGA_HS;
    CData/*0:0*/ top__DOT__VGA_VS;
    CData/*0:0*/ top__DOT__VGA_HB;
    CData/*0:0*/ top__DOT__VGA_VB;
    CData/*0:0*/ top__DOT__ioctl_download;
    CData/*0:0*/ top__DOT__ioctl_upload;
    CData/*0:0*/ top__DOT__ioctl_wr;
    CData/*7:0*/ top__DOT__ioctl_dout;
    CData/*7:0*/ top__DOT__ioctl_din;
    CData/*7:0*/ top__DOT__ioctl_index;
    CData/*0:0*/ top__DOT__ioctl_wait;
    CData/*0:0*/ top__DOT__ce_pix;
    CData/*7:0*/ top__DOT__ram_d;
    CData/*7:0*/ top__DOT__ram_d_temp;
    CData/*0:0*/ top__DOT__ram_we;
    CData/*0:0*/ top__DOT__ram_cs;
    CData/*0:0*/ top__DOT__ram_we_temp;
    CData/*0:0*/ top__DOT__ram_cs_temp;
    CData/*7:0*/ top__DOT__ram_q;
    CData/*0:0*/ top__DOT__video_clk;
    CData/*0:0*/ top__DOT__tape_wr;
    CData/*7:0*/ top__DOT__tape_dout;
    CData/*0:0*/ top__DOT__tape_complete;
    CData/*0:0*/ top__DOT__tape_autorun;
    CData/*0:0*/ top__DOT__tape_request;
    CData/*0:0*/ top__DOT__key_strobe;
    CData/*0:0*/ top__DOT__old_keystb;
    CData/*0:0*/ top__DOT__r;
    CData/*0:0*/ top__DOT__g;
    CData/*0:0*/ top__DOT__b;
    CData/*0:0*/ top__DOT__hs;
    CData/*0:0*/ top__DOT__vs;
    CData/*0:0*/ top__DOT__clk_pix2;
    CData/*0:0*/ top__DOT__fdd_ready;
    CData/*0:0*/ top__DOT__psg_a;
    CData/*0:0*/ top__DOT__psg_b;
    CData/*0:0*/ top__DOT__psg_c;
    CData/*0:0*/ top__DOT__psg_out;
    CData/*0:0*/ top__DOT__clk_pix;
    CData/*0:0*/ top__DOT__tape_adc;
    CData/*0:0*/ top__DOT__tape_out;
    CData/*0:0*/ top__DOT__led_disk;
    CData/*0:0*/ top__DOT__img_mounted;
    CData/*0:0*/ top__DOT__img_size;
    CData/*0:0*/ top__DOT__img_readonly;
    CData/*0:0*/ top__DOT__sd_lba;
    CData/*0:0*/ top__DOT__sd_rd;
    CData/*0:0*/ top__DOT__sd_wr;
    CData/*0:0*/ top__DOT__sd_ack;
    CData/*0:0*/ top__DOT__sd_buff_addr;
    CData/*0:0*/ top__DOT__sd_buff_dout;
    CData/*0:0*/ top__DOT__sd_buff_din;
    CData/*0:0*/ top__DOT__sd_buff_wr;
    CData/*0:0*/ top__DOT__unnamedblk1__DOT__old_clk;
    CData/*0:0*/ top__DOT__ram__DOT__clock;
    CData/*0:0*/ top__DOT__ram__DOT__ce1;
    CData/*0:0*/ top__DOT__ram__DOT__we1;
    CData/*7:0*/ top__DOT__ram__DOT__di1;
    CData/*7:0*/ top__DOT__ram__DOT__do1;
    CData/*0:0*/ top__DOT__ram__DOT__ce2;
    CData/*0:0*/ top__DOT__ram__DOT__we2;
    CData/*7:0*/ top__DOT__ram__DOT__di2;
    CData/*7:0*/ top__DOT__ram__DOT__do2;
    CData/*0:0*/ top__DOT__cassette__DOT__clk;
    CData/*0:0*/ top__DOT__cassette__DOT__ioctl_download;
    CData/*0:0*/ top__DOT__cassette__DOT__ioctl_wr;
    CData/*7:0*/ top__DOT__cassette__DOT__ioctl_dout;
    CData/*0:0*/ top__DOT__cassette__DOT__reset_n;
    CData/*0:0*/ top__DOT__cassette__DOT__tape_request;
    CData/*0:0*/ top__DOT__cassette__DOT__autostart;
    CData/*0:0*/ top__DOT__cassette__DOT__tape_autorun;
    CData/*0:0*/ top__DOT__cassette__DOT__tape_wr;
    CData/*7:0*/ top__DOT__cassette__DOT__tape_dout;
    CData/*0:0*/ top__DOT__cassette__DOT__tape_complete;
    CData/*7:0*/ top__DOT__cassette__DOT__fileType;
    CData/*7:0*/ top__DOT__cassette__DOT__autorun;
    CData/*7:0*/ top__DOT__cassette__DOT__endAddressHIGH;
    CData/*7:0*/ top__DOT__cassette__DOT__endAddressLOW;
    CData/*7:0*/ top__DOT__cassette__DOT__startAddressHIGH;
    CData/*7:0*/ top__DOT__cassette__DOT__startAddressLOW;
    CData/*0:0*/ top__DOT__cassette__DOT__unused;
    CData/*7:0*/ top__DOT__cassette__DOT__cache_dout;
    CData/*0:0*/ top__DOT__cassette__DOT__cache_cs;
    CData/*0:0*/ top__DOT__cassette__DOT__tapecache_loaded;
    CData/*0:0*/ top__DOT__cassette__DOT__ioctl_downlD;
    CData/*0:0*/ top__DOT__cassette__DOT__tapecache__DOT__clk;
    CData/*0:0*/ top__DOT__cassette__DOT__tapecache__DOT__bram_download;
    CData/*0:0*/ top__DOT__cassette__DOT__tapecache__DOT__bram_wr;
    CData/*7:0*/ top__DOT__cassette__DOT__tapecache__DOT__bram_din;
    CData/*0:0*/ top__DOT__cassette__DOT__tapecache__DOT__cs;
    CData/*7:0*/ top__DOT__cassette__DOT__tapecache__DOT__dout;
    CData/*0:0*/ top__DOT__oricatmos__DOT__CLK_IN;
    CData/*0:0*/ top__DOT__oricatmos__DOT__RESET;
    CData/*0:0*/ top__DOT__oricatmos__DOT__key_pressed;
    CData/*0:0*/ top__DOT__oricatmos__DOT__key_extended;
    CData/*7:0*/ top__DOT__oricatmos__DOT__key_code;
    CData/*0:0*/ top__DOT__oricatmos__DOT__key_strobe;
    CData/*0:0*/ top__DOT__oricatmos__DOT__K7_TAPEIN;
    CData/*0:0*/ top__DOT__oricatmos__DOT__K7_TAPEOUT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__K7_REMOTE;
    CData/*7:0*/ top__DOT__oricatmos__DOT__PSG_OUT_A;
    CData/*7:0*/ top__DOT__oricatmos__DOT__PSG_OUT_B;
    CData/*7:0*/ top__DOT__oricatmos__DOT__PSG_OUT_C;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_CLK;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_R;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_G;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_B;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_HBLANK;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_VBLANK;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_HSYNC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_VSYNC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__VIDEO_SYNC;
    CData/*7:0*/ top__DOT__oricatmos__DOT__ram_d;
    CData/*7:0*/ top__DOT__oricatmos__DOT__ram_q;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ram_cs;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ram_oe;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ram_we;
    CData/*0:0*/ top__DOT__oricatmos__DOT__phi2;
    CData/*0:0*/ top__DOT__oricatmos__DOT__fd_led;
    CData/*0:0*/ top__DOT__oricatmos__DOT__fdd_ready;
    CData/*0:0*/ top__DOT__oricatmos__DOT__fdd_busy;
    CData/*0:0*/ top__DOT__oricatmos__DOT__fdd_reset;
    CData/*0:0*/ top__DOT__oricatmos__DOT__fdd_layout;
    CData/*7:0*/ top__DOT__oricatmos__DOT__joystick_0;
    CData/*7:0*/ top__DOT__oricatmos__DOT__joystick_1;
    CData/*0:0*/ top__DOT__oricatmos__DOT__pll_locked;
    CData/*0:0*/ top__DOT__oricatmos__DOT__disk_enable;
    CData/*0:0*/ top__DOT__oricatmos__DOT__rom;
    CData/*0:0*/ top__DOT__oricatmos__DOT__img_mounted;
    CData/*0:0*/ top__DOT__oricatmos__DOT__img_wp;
    CData/*0:0*/ top__DOT__oricatmos__DOT__sd_rd;
    CData/*0:0*/ top__DOT__oricatmos__DOT__sd_wr;
    CData/*0:0*/ top__DOT__oricatmos__DOT__sd_ack;
    CData/*7:0*/ top__DOT__oricatmos__DOT__sd_dout;
    CData/*7:0*/ top__DOT__oricatmos__DOT__sd_din;
    CData/*0:0*/ top__DOT__oricatmos__DOT__sd_dout_strobe;
    CData/*0:0*/ top__DOT__oricatmos__DOT__sd_din_strobe;
    CData/*0:0*/ top__DOT__oricatmos__DOT__tape_complete;
    CData/*0:0*/ top__DOT__oricatmos__DOT__RESETn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__reset_dll_h;
    CData/*7:0*/ top__DOT__oricatmos__DOT__delay_count;
    CData/*2:0*/ top__DOT__oricatmos__DOT__clk_cnt;
    CData/*7:0*/ top__DOT__oricatmos__DOT__cpu_di;
    CData/*7:0*/ top__DOT__oricatmos__DOT__cpu_do;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cpu_rw;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cpu_irq;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pa_out_oe;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pa_in;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pa_out;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pa_in_from_psg;
    CData/*0:0*/ top__DOT__oricatmos__DOT__via_cb1_out;
    CData/*0:0*/ top__DOT__oricatmos__DOT__via_cb1_oe_l;
    CData/*0:0*/ top__DOT__oricatmos__DOT__via_cb2_out;
    CData/*0:0*/ top__DOT__oricatmos__DOT__via_cb2_oe_l;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_in;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_out;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_oe_l;
    CData/*7:0*/ top__DOT__oricatmos__DOT__VIA_DO;
    CData/*7:0*/ top__DOT__oricatmos__DOT__KEY_ROW;
    CData/*0:0*/ top__DOT__oricatmos__DOT__KEYB_RESETn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__KEYB_NMIn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__psg_bdir;
    CData/*0:0*/ top__DOT__oricatmos__DOT__psg_bc1;
    CData/*7:0*/ top__DOT__oricatmos__DOT__ym_o_ioa;
    CData/*0:0*/ top__DOT__oricatmos__DOT__psg_sample_ok;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_phi2;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_CSIOn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_CSROMn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_CSRAMn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_CE_SRAM;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_OE_SRAM;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_WE_SRAM;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_LATCH_SRAM;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_CLK_4;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_CLK_4_en;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_MUX;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_RW_RAM;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_VIDEO_R;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_VIDEO_G;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ula_VIDEO_B;
    CData/*0:0*/ top__DOT__oricatmos__DOT__ENA_1MHZ;
    CData/*7:0*/ top__DOT__oricatmos__DOT__ROM_ATMOS_DO;
    CData/*7:0*/ top__DOT__oricatmos__DOT__ROM_1_DO;
    CData/*7:0*/ top__DOT__oricatmos__DOT__ROM_MD_DO;
    CData/*0:0*/ top__DOT__oricatmos__DOT__PRN_STROBE;
    CData/*7:0*/ top__DOT__oricatmos__DOT__PRN_DATA;
    CData/*7:0*/ top__DOT__oricatmos__DOT__SRAM_DO;
    CData/*0:0*/ top__DOT__oricatmos__DOT__swnmi;
    CData/*0:0*/ top__DOT__oricatmos__DOT__swrst;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_MAPn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_ROMDISn;
    CData/*7:0*/ top__DOT__oricatmos__DOT__cont_D_OUT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_IOCONTROLn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_ECE;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_nOE;
    CData/*0:0*/ top__DOT__oricatmos__DOT__cont_irq;
    CData/*0:0*/ top__DOT__oricatmos__DOT__PH2_1;
    CData/*0:0*/ top__DOT__oricatmos__DOT__PH2_2;
    CData/*0:0*/ top__DOT__oricatmos__DOT__PH2_3;
    CData/*3:0*/ top__DOT__oricatmos__DOT__PH2_old;
    CData/*4:0*/ top__DOT__oricatmos__DOT__PH2_cntr;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Mode;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Res_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Enable;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Clk;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Rdy;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Abort_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__IRQ_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__NMI_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__SO_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__R_W_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Sync;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__EF;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__MF;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__XF;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__ML_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__VP_n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__VDA;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__VPA;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DI;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DO;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DEBUG_I;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DEBUG_A;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DEBUG_X;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DEBUG_Y;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DEBUG_S;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DEBUG_P;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__NMI_ack;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__PRINT;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__tape_addr;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__tape_complete;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__P;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__AD;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DL;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__PwithB;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BAH;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__PBR;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DBR;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__EF_i;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__MF_i;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__XF_i;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__IR;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__MCycle;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__DO_r;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Mode_r;
    CData/*4:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__ALU_Op_r;
    CData/*3:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Write_Data_r;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Set_Addr_To_r;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__RstCycle;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__IRQCycle;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__NMICycle;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__SO_n_o;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__IRQ_n_o;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__NMI_n_o;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__NMIAct;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Break;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BusA;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BusA_r;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BusB;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BusB_r;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__ALU_Q;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__P_Out;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LCycle;
    CData/*4:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__ALU_Op;
    CData/*3:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Set_BusA_To;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Set_Addr_To;
    CData/*3:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Write_Data;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Jump;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BAAdd;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BAQuirk;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BreakAtNA;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__ADAdd;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__AddY;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__PCAdd;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Inc_S;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Dec_S;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDA;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDP;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDX;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDY;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDS;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDDI;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDALU;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDAD;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDBAL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__LDBAH;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__SaveP;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Write;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Res_n_d;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__rdy_mod;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__really_rdy;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__WRn_i;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__NMI_entered;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__xhdl0__DOT__tmpP;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Mode;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__IR;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__MCycle;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__P;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Rdy_mod;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LCycle;
    CData/*4:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__ALU_Op;
    CData/*3:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Set_BusA_To;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Set_Addr_To;
    CData/*3:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Write_Data;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Jump;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__BAAdd;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__BAQuirk;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__BreakAtNA;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__ADAdd;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__AddY;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__PCAdd;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Inc_S;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Dec_S;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDA;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDP;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDX;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDY;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDS;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDDI;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDALU;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDAD;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDBAL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__LDBAH;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__SaveP;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Write;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Branch;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__ALUmore;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Mode;
    CData/*4:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Op;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__BusA;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__BusB;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__P_In;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__P_Out;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Q;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__ADC_Z;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__ADC_C;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__ADC_V;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__ADC_N;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__ADC_Q;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__SBC_Z;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__SBC_C;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__SBC_V;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__SBC_N;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__SBC_Q;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__SBX_Q;
    CData/*6:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl0__DOT__AL;
    CData/*6:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl0__DOT__AH;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl0__DOT__C;
    CData/*6:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl1__DOT__AL;
    CData/*5:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl1__DOT__AH;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl1__DOT__C;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl1__DOT__CT;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl2__DOT__Q_t;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__xhdl2__DOT__Q2_t;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_rom0__DOT__clk;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_rom0__DOT__data;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_rom1__DOT__clk;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_rom1__DOT__data;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_rom2__DOT__clk;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_rom2__DOT__data;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__RESETn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_4;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_4_EN;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__PHI2;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__PHI2_EN;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__RW;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__MAPn;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__DB;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CSRAMn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__SRAM_OE;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__SRAM_CE;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__SRAM_WE;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__LATCH_SRAM;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CSIOn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CSROMn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__R;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__G;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__B;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__SYNC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_PIX;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__HBLANK;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__VBLANK;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__HSYNC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__VSYNC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_4_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_1_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_1_EN;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_PIXEL_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_FLASH;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__DB_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__RW_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lHIRES_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__HIRES_DEC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lDBLHGT_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lALT_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lFORCETXT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__isAttrib;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__ATTRIB_DEC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__RELD_REG;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__DATABUS_EN;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lCOMPSYNC;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lHSYNCn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lVSYNC50n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lVSYNC60n;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lVSYNCn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__BLANKINGn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lFREQ_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__LDFROMBUS;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CHROWCNT;
    CData/*6:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lCTR_H;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__RGB_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CSRAMn_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CSIOn_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CSROMn_INT;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lMAPn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__DBLHGT_EN;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__ph;
    CData/*4:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lCTR_FLASH;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lVBLANKn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lHBLANKn;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lDATABUS;
    CData/*5:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lSHFREG;
    CData/*6:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lREGHOLD;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lRGB;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lREG_INK;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lREG_STYLE;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lREG_PAPER;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lREG_MODE;
    CData/*1:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__ModeStyle;
    CData/*5:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lADD;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lInv;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lInv_hold;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lBGFG_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lFLASH_SEL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__clk_sys;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__reset;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__key_pressed;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__key_extended;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__key_strobe;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__key_code;
    CData/*2:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__col;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__row;
    CData/*7:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__ROWbit;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swrst;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swnmi;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw0;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw1;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw2;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw3;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw4;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw5;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw6;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw7;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw8;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sw9;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swa;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swb;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swc;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swd;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swe;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swg;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swh;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swi;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swj;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swk;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swl;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swm;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swo;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swp;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swq;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swr;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sws;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swt;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swu;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swv;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sww;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swx;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swy;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swz;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swU;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swD;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swL;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swR;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swrs;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swls;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swsp;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swcom;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swdot;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swret;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swfs;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__sweq;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swfcn;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swdel;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swrsb;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swlsb;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swbs;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swdsh;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swsq;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swsc;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swesc;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swctl;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf1;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf2;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf3;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf4;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf5;
    CData/*0:0*/ top__DOT__oricatmos__DOT__inst_key__DOT__swf6;
    SData/*11:0*/ top__DOT__inputs;
    SData/*15:0*/ top__DOT__AUDIO_L;
    SData/*15:0*/ top__DOT__AUDIO_R;
    SData/*10:0*/ top__DOT__ps2_key;
    SData/*15:0*/ top__DOT__ram_ad;
    SData/*15:0*/ top__DOT__ram_ad_temp;
    SData/*15:0*/ top__DOT__tape_addr;
    SData/*15:0*/ top__DOT__loadpoint;
    SData/*15:0*/ top__DOT__tape_read_addr;
    SData/*15:0*/ top__DOT__tape_read_dout;
    SData/*15:0*/ top__DOT__ram__DOT__a1;
    SData/*15:0*/ top__DOT__ram__DOT__a2;
    SData/*15:0*/ top__DOT__cassette__DOT__loadpoint;
    SData/*15:0*/ top__DOT__cassette__DOT__tape_addr;
    SData/*15:0*/ top__DOT__cassette__DOT__programlength;
    SData/*15:0*/ top__DOT__cassette__DOT__start_addr;
    SData/*15:0*/ top__DOT__cassette__DOT__end_addr;
    SData/*15:0*/ top__DOT__cassette__DOT__state;
    SData/*15:0*/ top__DOT__cassette__DOT__cache_addr;
    SData/*15:0*/ top__DOT__cassette__DOT__tapecache__DOT__bram_init_address;
    SData/*15:0*/ top__DOT__cassette__DOT__tapecache__DOT__addr;
    SData/*9:0*/ top__DOT__oricatmos__DOT__PSG_OUT;
    SData/*15:0*/ top__DOT__oricatmos__DOT__ram_ad;
    SData/*8:0*/ top__DOT__oricatmos__DOT__sd_buff_addr;
    SData/*15:0*/ top__DOT__oricatmos__DOT__tape_addr;
    SData/*15:0*/ top__DOT__oricatmos__DOT__ula_AD_SRAM;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__ABC;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__X;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Y;
    SData/*8:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__BAL;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__PC;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__S;
    SData/*8:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__PCAdder;
    SData/*13:0*/ top__DOT__oricatmos__DOT__inst_rom0__DOT__addr;
    SData/*13:0*/ top__DOT__oricatmos__DOT__inst_rom1__DOT__addr;
    SData/*12:0*/ top__DOT__oricatmos__DOT__inst_rom2__DOT__addr;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__ADDR;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__SRAM_AD;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__VAP1;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__VAP2;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lADDR;
    SData/*8:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__lCTR_V;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__AD_RAM_INT;
    SData/*8:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__CTR_V_DIV8;
    SData/*15:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__voffset;
    SData/*14:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__mulBy40;
    IData/*24:0*/ top__DOT__ioctl_addr;
    IData/*16:0*/ top__DOT__clr_addr;
    IData/*24:0*/ top__DOT__cassette__DOT__ioctl_addr;
    IData/*31:0*/ top__DOT__oricatmos__DOT__img_size;
    IData/*31:0*/ top__DOT__oricatmos__DOT__sd_lba;
    IData/*23:0*/ top__DOT__oricatmos__DOT__cpu_ad;
    IData/*23:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__A;
    IData/*23:0*/ top__DOT__oricatmos__DOT__inst_ula__DOT__c;
    QData/*63:0*/ top__DOT__oricatmos__DOT__inst_cpu__DOT__Regs;
    VlUnpacked<CData/*7:0*/, 65536> top__DOT__ram__DOT__d;
    VlUnpacked<CData/*7:0*/, 65536> top__DOT__cassette__DOT__tapecache__DOT__memory;
    VlUnpacked<CData/*7:0*/, 16384> top__DOT__oricatmos__DOT__inst_rom0__DOT__rom_data;
    VlUnpacked<CData/*7:0*/, 16384> top__DOT__oricatmos__DOT__inst_rom1__DOT__rom_data;
    VlUnpacked<CData/*7:0*/, 8192> top__DOT__oricatmos__DOT__inst_rom2__DOT__rom_data;

    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    CData/*7:0*/ top__DOT____Vcellout__oricatmos__sd_din;
    CData/*7:0*/ top__DOT____Vcellout__oricatmos__PSG_OUT_C;
    CData/*7:0*/ top__DOT____Vcellout__oricatmos__PSG_OUT_B;
    CData/*7:0*/ top__DOT____Vcellout__oricatmos__PSG_OUT_A;
    CData/*0:0*/ top__DOT__oricatmos__DOT____Vcellinp__inst_cpu__IRQ_n;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_in__out0;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_in__out1;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_in__out2;
    CData/*7:0*/ top__DOT__oricatmos__DOT__via_pb_in__out3;
    CData/*7:0*/ __Vdly__top__DOT__cassette__DOT__endAddressHIGH;
    CData/*7:0*/ __Vdly__top__DOT__cassette__DOT__endAddressLOW;
    CData/*7:0*/ __Vdly__top__DOT__cassette__DOT__startAddressHIGH;
    CData/*7:0*/ __Vdly__top__DOT__cassette__DOT__startAddressLOW;
    CData/*0:0*/ __Vdly__top__DOT__tape_wr;
    CData/*0:0*/ __Vdly__top__DOT__tape_complete;
    CData/*7:0*/ __Vdlyvval__top__DOT__cassette__DOT__tapecache__DOT__memory__v0;
    CData/*0:0*/ __Vdlyvset__top__DOT__cassette__DOT__tapecache__DOT__memory__v0;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__oricatmos__DOT__inst_cpu__DOT__Res_n_i;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__RESET_INT;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__lRELOAD_SEL;
    CData/*0:0*/ __Vclklast__TOP__clk_48;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__oricatmos__DOT__cont_RESETn;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__oricatmos__DOT__inst_cpu__DOT__Res_n_i;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__CLK_24;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__RESET_INT;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__lRELOAD_SEL;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__oricatmos__DOT__inst_cpu__DOT__Res_n_i;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__lRELOAD_SEL;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__oricatmos__DOT__inst_ula__DOT__RESET_INT;
    SData/*9:0*/ top__DOT____Vcellout__oricatmos__PSG_OUT;
    SData/*10:0*/ __Vtableidx1;
    SData/*15:0*/ __Vdly__top__DOT__cassette__DOT__state;
    SData/*15:0*/ __Vdly__top__DOT__cassette__DOT__cache_addr;
    SData/*15:0*/ __Vdly__top__DOT__cassette__DOT__end_addr;
    SData/*15:0*/ __Vdly__top__DOT__cassette__DOT__start_addr;
    SData/*15:0*/ __Vdlyvdim0__top__DOT__cassette__DOT__tapecache__DOT__memory__v0;
    IData/*31:0*/ top__DOT____Vcellout__oricatmos__sd_lba;
    IData/*23:0*/ __Vdly__top__DOT__oricatmos__DOT__inst_ula__DOT__c;
    static VlUnpacked<CData/*4:0*/, 2048> __Vtable1_top__DOT__oricatmos__DOT__inst_cpu__DOT__ALU_Op;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;

    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vtop__Syms* __VlSymsp;  // Symbol table

    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    enum _IDatatop__DOT__ram__DOT__DW { top__DOT__ram__DOT__DW = 8U};
    static const IData var_top__DOT__ram__DOT__DW;
    enum _IDatatop__DOT__ram__DOT__AW { top__DOT__ram__DOT__AW = 0x10U};
    static const IData var_top__DOT__ram__DOT__AW;
    enum _IDatatop__DOT__cassette__DOT__SM_INIT { top__DOT__cassette__DOT__SM_INIT = 1U};
    static const IData var_top__DOT__cassette__DOT__SM_INIT;
    enum _IDatatop__DOT__cassette__DOT__SM_FILETYPE { top__DOT__cassette__DOT__SM_FILETYPE = 2U};
    static const IData var_top__DOT__cassette__DOT__SM_FILETYPE;
    enum _IDatatop__DOT__cassette__DOT__SM_AUTORUN { top__DOT__cassette__DOT__SM_AUTORUN = 3U};
    static const IData var_top__DOT__cassette__DOT__SM_AUTORUN;
    enum _IDatatop__DOT__cassette__DOT__SM_ENDADDRESSHIGH { top__DOT__cassette__DOT__SM_ENDADDRESSHIGH = 4U};
    static const IData var_top__DOT__cassette__DOT__SM_ENDADDRESSHIGH;
    enum _IDatatop__DOT__cassette__DOT__SM_ENDADDRESSLOW { top__DOT__cassette__DOT__SM_ENDADDRESSLOW = 5U};
    static const IData var_top__DOT__cassette__DOT__SM_ENDADDRESSLOW;
    enum _IDatatop__DOT__cassette__DOT__SM_STARTADDRESSHIGH { top__DOT__cassette__DOT__SM_STARTADDRESSHIGH = 6U};
    static const IData var_top__DOT__cassette__DOT__SM_STARTADDRESSHIGH;
    enum _IDatatop__DOT__cassette__DOT__SM_STARTADDRESSLOW { top__DOT__cassette__DOT__SM_STARTADDRESSLOW = 7U};
    static const IData var_top__DOT__cassette__DOT__SM_STARTADDRESSLOW;
    enum _IDatatop__DOT__cassette__DOT__SM_FILENAME { top__DOT__cassette__DOT__SM_FILENAME = 8U};
    static const IData var_top__DOT__cassette__DOT__SM_FILENAME;
    enum _IDatatop__DOT__cassette__DOT__SM_PROGRAMCODE { top__DOT__cassette__DOT__SM_PROGRAMCODE = 9U};
    static const IData var_top__DOT__cassette__DOT__SM_PROGRAMCODE;
    enum _IDatatop__DOT__cassette__DOT__SM_COMPLETE { top__DOT__cassette__DOT__SM_COMPLETE = 0xaU};
    static const IData var_top__DOT__cassette__DOT__SM_COMPLETE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_C { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_C = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_C;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_Z { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_Z = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_Z;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_I { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_I = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_I;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_D { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_D = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_D;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_B { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_B = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_B;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_1 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_V { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_V = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_V;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_N { top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_N = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Flag_N;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_sync { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_sync = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_sync;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_1 = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_2 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_2 = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_2;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_3 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_3 = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_3;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_4 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_4 = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_4;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_5 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_5 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_5;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_6 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_6 = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_6;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_7 { top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_7 = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__Cycle_7;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DI { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DI = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DI;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_ABC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_ABC = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_ABC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_X { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_X = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_X;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_Y { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_Y = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_Y;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_S { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_S = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_S;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_P { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_P = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_P;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DA { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DA = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DAO { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DAO = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DAO;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DAX = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_AAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_AAX = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_AAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_PBR { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_PBR = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_PBR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_SP { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_SP = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_SP;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_ZPG { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_ZPG = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_ZPG;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_BA { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_BA = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Set_Addr_To_Set_Addr_To_BA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_DL { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_DL = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_DL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_ABC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_ABC = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_ABC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_X { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_X = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_X;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_Y { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_Y = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_Y;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_S { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_S = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_S;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_P { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_P = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_P;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_PCL { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_PCL = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_PCL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_PCH { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_PCH = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_PCH;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_AX { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_AX = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_AX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_AXB { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_AXB = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_AXB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_XB { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_XB = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_XB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_YB { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_YB = 0xbU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_YB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_DONTCARE { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_DONTCARE = 0xcU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_Write_Data_Write_Data_DONTCARE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_OR { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_OR = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_OR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_AND { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_AND = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_AND;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EOR { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EOR = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EOR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ADC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ADC = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ADC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EQ1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EQ1 = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EQ1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EQ2 { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EQ2 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_EQ2;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_CMP { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_CMP = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_CMP;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_SBC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_SBC = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_SBC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ASL { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ASL = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ASL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ROL { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ROL = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ROL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_LSR { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_LSR = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_LSR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ROR { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ROR = 0xbU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ROR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_BIT { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_BIT = 0xcU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_BIT;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_DEC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_DEC = 0xdU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_DEC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_INC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_INC = 0xeU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_INC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ARR { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ARR = 0xfU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ARR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ANC { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ANC = 0x10U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_ANC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_SAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_SAX = 0x11U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_SAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_XAA { top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_XAA = 0x12U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__T_ALU_OP_ALU_OP_XAA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_C { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_C = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_C;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_Z { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_Z = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_Z;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_I { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_I = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_I;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_D { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_D = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_D;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_B { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_B = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_B;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_1 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_V { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_V = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_V;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_N { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_N = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Flag_N;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_sync { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_sync = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_sync;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_1 = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_2 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_2 = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_2;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_3 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_3 = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_3;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_4 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_4 = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_4;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_5 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_5 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_5;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_6 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_6 = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_6;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_7 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_7 = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__Cycle_7;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DI { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DI = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DI;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_ABC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_ABC = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_ABC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_X { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_X = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_X;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_Y { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_Y = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_Y;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_S { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_S = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_S;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_P { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_P = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_P;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DA { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DA = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DAO { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DAO = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DAO;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DAX = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_AAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_AAX = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_AAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_PBR { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_PBR = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_PBR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_SP { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_SP = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_SP;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_ZPG { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_ZPG = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_ZPG;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_BA { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_BA = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Set_Addr_To_Set_Addr_To_BA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_DL { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_DL = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_DL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_ABC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_ABC = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_ABC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_X { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_X = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_X;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_Y { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_Y = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_Y;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_S { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_S = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_S;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_P { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_P = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_P;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_PCL { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_PCL = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_PCL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_PCH { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_PCH = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_PCH;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_AX { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_AX = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_AX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_AXB { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_AXB = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_AXB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_XB { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_XB = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_XB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_YB { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_YB = 0xbU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_YB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_DONTCARE { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_DONTCARE = 0xcU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_Write_Data_Write_Data_DONTCARE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_OR { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_OR = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_OR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_AND { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_AND = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_AND;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EOR { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EOR = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EOR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ADC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ADC = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ADC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EQ1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EQ1 = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EQ1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EQ2 { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EQ2 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_EQ2;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_CMP { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_CMP = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_CMP;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_SBC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_SBC = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_SBC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ASL { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ASL = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ASL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ROL { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ROL = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ROL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_LSR { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_LSR = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_LSR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ROR { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ROR = 0xbU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ROR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_BIT { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_BIT = 0xcU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_BIT;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_DEC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_DEC = 0xdU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_DEC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_INC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_INC = 0xeU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_INC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ARR { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ARR = 0xfU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ARR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ANC { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ANC = 0x10U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_ANC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_SAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_SAX = 0x11U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_SAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_XAA { top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_XAA = 0x12U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__mcode__DOT__T_ALU_OP_ALU_OP_XAA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_C { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_C = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_C;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_Z { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_Z = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_Z;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_I { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_I = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_I;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_D { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_D = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_D;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_B { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_B = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_B;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_1 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_V { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_V = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_V;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_N { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_N = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Flag_N;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_sync { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_sync = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_sync;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_1 = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_2 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_2 = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_2;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_3 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_3 = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_3;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_4 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_4 = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_4;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_5 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_5 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_5;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_6 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_6 = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_6;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_7 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_7 = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__Cycle_7;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DI { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DI = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DI;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_ABC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_ABC = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_ABC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_X { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_X = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_X;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_Y { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_Y = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_Y;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_S { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_S = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_S;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_P { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_P = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_P;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DA { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DA = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DAO { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DAO = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DAO;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DAX = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_AAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_AAX = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_AAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_BusA_To_Set_BusA_To_DONTCARE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_PBR { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_PBR = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_PBR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_SP { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_SP = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_SP;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_ZPG { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_ZPG = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_ZPG;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_BA { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_BA = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Set_Addr_To_Set_Addr_To_BA;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_DL { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_DL = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_DL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_ABC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_ABC = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_ABC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_X { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_X = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_X;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_Y { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_Y = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_Y;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_S { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_S = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_S;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_P { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_P = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_P;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_PCL { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_PCL = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_PCL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_PCH { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_PCH = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_PCH;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_AX { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_AX = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_AX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_AXB { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_AXB = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_AXB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_XB { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_XB = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_XB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_YB { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_YB = 0xbU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_YB;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_DONTCARE { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_DONTCARE = 0xcU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_Write_Data_Write_Data_DONTCARE;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_OR { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_OR = 0U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_OR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_AND { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_AND = 1U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_AND;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EOR { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EOR = 2U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EOR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ADC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ADC = 3U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ADC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EQ1 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EQ1 = 4U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EQ1;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EQ2 { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EQ2 = 5U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_EQ2;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_CMP { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_CMP = 6U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_CMP;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_SBC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_SBC = 7U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_SBC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ASL { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ASL = 8U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ASL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ROL { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ROL = 9U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ROL;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_LSR { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_LSR = 0xaU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_LSR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ROR { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ROR = 0xbU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ROR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_BIT { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_BIT = 0xcU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_BIT;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_DEC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_DEC = 0xdU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_DEC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_INC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_INC = 0xeU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_INC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ARR { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ARR = 0xfU};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ARR;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ANC { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ANC = 0x10U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_ANC;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_SAX { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_SAX = 0x11U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_SAX;
    enum _IDatatop__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_XAA { top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_XAA = 0x12U};
    static const IData var_top__DOT__oricatmos__DOT__inst_cpu__DOT__alu__DOT__T_ALU_OP_ALU_OP_XAA;

    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    Vtop(VerilatedContext* contextp, const char* name = "TOP");
    Vtop(const char* name = "TOP")
      : Vtop(nullptr, name) {}
    /// Destroy the model; called (often implicitly) by application code
    ~Vtop();
    /// Trace signals in the model; called by application code
    void trace(VerilatedVcdC* tfp, int levels, int options = 0);

    // API METHODS
    /// Return current simulation context for this model.
    /// Used to get to e.g. simulation time via contextp()->time()
    VerilatedContext* contextp();
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();

    // INTERNAL METHODS
    static void _eval_initial_loop(Vtop__Syms* __restrict vlSymsp);
    void __Vconfigure(Vtop__Syms* symsp, bool first);
  private:
    static QData _change_request(Vtop__Syms* __restrict vlSymsp);
    static QData _change_request_1(Vtop__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__14(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__24(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__29(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__35(Vtop__Syms* __restrict vlSymsp);
  private:
    static void _ctor_var_reset(Vtop* self) VL_ATTR_COLD;
  public:
    static void _eval(Vtop__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__1(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__10(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__11(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__2(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__3(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__4(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__5(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__6(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__7(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__8(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__9(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _multiclk__TOP__32(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__17(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__18(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__19(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__20(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__21(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__22(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__23(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__25(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__26(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__27(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__28(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__30(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__31(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__33(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__34(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__12(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__13(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
  private:
    static void traceChgSub0(void* userp, VerilatedVcd* tracep);
    static void traceChgTop0(void* userp, VerilatedVcd* tracep);
    static void traceCleanup(void* userp, VerilatedVcd* /*unused*/);
    static void traceFullSub0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceFullTop0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInitSub0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInitTop(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    void traceRegister(VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
  public:
    void __Vserialize(VerilatedSerialize& os);
    void __Vdeserialize(VerilatedDeserialize& os);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


inline VerilatedSerialize& operator<<(VerilatedSerialize& os, Vtop& rhs) {
    Verilated::quiesce(); rhs.__Vserialize(os); return os; }
inline VerilatedDeserialize& operator>>(VerilatedDeserialize& os, Vtop& rhs) {
    Verilated::quiesce(); rhs.__Vdeserialize(os); return os; }

#endif  // guard
